# Generated by Django 5.2.6 on 2026-01-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='temp', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
