# Generated by Django 5.2.6 on 2026-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_options_course_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-time_create'], name='core_course_time_cr_129bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='core_course_slug_ed28d0_idx'),
        ),
    ]
