# Generated by Django 5.2.6 on 2026-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parent_teacher'),
        ('core', '0005_tag_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='accounts.teacher', verbose_name='Преподаватели'),
        ),
    ]
