# Generated by Django 5.2.6 on 2026-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1, verbose_name='Статус'),
        ),
    ]
