# Generated by Django 5.2.6 on 2026-04-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, verbose_name='Имя ребёнка')),
                ('child_age', models.IntegerField(verbose_name='Возраст ребёнка')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Имя родителя')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Email родителя')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
