# Generated by Django 5.2.6 on 2026-02-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, verbose_name='Адрес')),
                ('status', models.IntegerField(choices=[(1, 'Активный'), (0, 'Неактивный'), (2, 'Выпускник')], default=1, verbose_name='Статус')),
                ('enrolled_date', models.DateField(auto_now=True, verbose_name='Даты регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
