# Generated by Django 5.2.6 on 2026-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parent_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
    ]
