# Generated by Django 5.2.6 on 2026-02-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_pupil_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='enrolled_date',
            field=models.DateField(auto_now_add=True, verbose_name='Даты регистрации'),
        ),
    ]
