# Generated by Django 5.2.6 on 2026-02-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pupil_enrolled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='accounts.pupil', verbose_name='Дети'),
        ),
    ]
