# Generated by Django 5.2.6 on 2026-05-04 07:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
                ('start_date', models.DateField(verbose_name='Дата создание')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.IntegerField(choices=[(1, 'Активна'), (2, 'Завершена'), (3, 'Запланирована')], default=1, verbose_name='Статус')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата зачисления')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата отчисления')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_enrollments', to='accounts.pupil', verbose_name='Ученик')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments', to='schedule.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Дата оплаты')),
                ('purpose', models.IntegerField(choices=[(0, 'Обучение'), (1, 'Материалы'), (2, 'Прочее')], default=0, verbose_name='Назначение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.pupil', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10, null=True, verbose_name='День недели')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='draft', max_length=20)),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('lesson_date', models.DateField(verbose_name='Дата занятия')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Тема занятия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_lessons', to='accounts.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['-lesson_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Присутствовал'), (0, 'Отсутствовал'), (2, 'Опоздал')], default=1)),
                ('notes', models.TextField(blank=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.pupil', verbose_name='Ученик')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schedule.schedule', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемости',
            },
        ),
        migrations.CreateModel(
            name='ScheduleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На согласовании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('course_name', models.CharField(max_length=200, verbose_name='Название направления')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('weekday1', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10, verbose_name='Первый день недели')),
                ('weekday2', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10, verbose_name='Второй день недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Заявка на расписание',
                'verbose_name_plural': 'Заявки на расписание',
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_group_per_course'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['-lesson_date'], name='schedule_sc_lesson__baab91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lesson', 'pupil')},
        ),
    ]
