# Generated by Django 5.2.6 on 2026-02-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
                ('start_date', models.DateField(verbose_name='Дата создание')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.IntegerField(choices=[(1, 'Активна'), (2, 'Завершена'), (3, 'Запланирована')], default=1, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата зачисления')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата отчисления')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_enrollments', to='accounts.pupil', verbose_name='Ученик')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments', to='schedule.group', verbose_name='Группа')),
            ],
        ),
    ]
