# Generated by Django 5.2.6 on 2026-02-10 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-date_from'], 'verbose_name': 'Зачисление', 'verbose_name_plural': 'Зачисления'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-start_date'], 'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Дата занятий')),
                ('status', models.IntegerField(choices=[(1, 'Присутствовал'), (0, 'Отсутствовал'), (2, 'Опоздал')], default=1, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.pupil', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемости',
                'ordering': ['-lesson_date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Дата занятия')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Тема занятия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['-lesson_date', 'start_time'],
                'indexes': [models.Index(fields=['-lesson_date'], name='schedule_sc_lesson__baab91_idx')],
            },
        ),
    ]
