# Generated by Django 5.2.6 on 2026-05-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Присутствовал'), (0, 'Отсутствовал'), (2, 'Опоздал')], default=1, verbose_name='Статус'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lesson',
        ),
    ]
