# Generated by Django 5.2.6 on 2026-02-10 07:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schedule', '0002_alter_enrollment_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Дата оплаты')),
                ('purpose', models.IntegerField(choices=[(0, 'Обучение'), (1, 'Материалы'), (2, 'Прочее')], default=0, verbose_name='Назначение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.pupil', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
    ]
