# Generated by Django 5.2.6 on 2026-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schedule', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('schedule', 'pupil'), name='unique_attendance_per_schedule_pupil'),
        ),
    ]
