# Generated by Django 5.2.6 on 2026-02-11 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_pupil_address'),
        ('schedule', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_lessons', to='accounts.teacher', verbose_name='Преподаватель'),
        ),
    ]
