# Generated by Django 5.2.6 on 2026-04-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_application'),
        ('schedule', '0004_schedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.course', verbose_name='Курс'),
        ),
    ]
