# Generated by Django 5.2.6 on 2026-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='draft', max_length=20),
        ),
    ]
