# Generated by Django 5.2.6 on 2026-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(blank=True, choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10, null=True, verbose_name='День недели'),
        ),
    ]
