# Generated by Django 5.2.6 on 2026-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_schedule_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кабинет'),
        ),
    ]
