# Generated by Django 5.2.6 on 2026-05-03 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_manager'),
        ('schedule', '0008_schedule_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На согласовании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('course_name', models.CharField(max_length=200, verbose_name='Название направления')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('weekday1', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10, verbose_name='Первый день недели')),
                ('weekday2', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=10, verbose_name='Второй день недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Заявка на расписание',
                'verbose_name_plural': 'Заявки на расписание',
            },
        ),
    ]
