# Generated by Django 5.2.6 on 2026-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_application'),
        ('schedule', '0009_scheduleproposal'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_group_per_course'),
        ),
    ]
